spring.datasource.url=jdbc:mysql://mojomusicdb.cn60gsekuol0.ap-south-1.rds.amazonaws.com:3306/MusicMojo
spring.datasource.username=admin
spring.datasource.password=adminadmin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
